// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/1359332949/douyin/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PublishAction": kitex.NewMethodInfo(publishActionHandler, newUserServicePublishActionArgs, newUserServicePublishActionResult, false),
		"PublishList":   kitex.NewMethodInfo(publishListHandler, newUserServicePublishListArgs, newUserServicePublishListResult, false),
		"GetUserFeed":   kitex.NewMethodInfo(getUserFeedHandler, newUserServiceGetUserFeedArgs, newUserServiceGetUserFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func publishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServicePublishActionArgs)
	realResult := result.(*user.UserServicePublishActionResult)
	success, err := handler.(user.UserService).PublishAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServicePublishActionArgs() interface{} {
	return user.NewUserServicePublishActionArgs()
}

func newUserServicePublishActionResult() interface{} {
	return user.NewUserServicePublishActionResult()
}

func publishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServicePublishListArgs)
	realResult := result.(*user.UserServicePublishListResult)
	success, err := handler.(user.UserService).PublishList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServicePublishListArgs() interface{} {
	return user.NewUserServicePublishListArgs()
}

func newUserServicePublishListResult() interface{} {
	return user.NewUserServicePublishListResult()
}

func getUserFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserFeedArgs)
	realResult := result.(*user.UserServiceGetUserFeedResult)
	success, err := handler.(user.UserService).GetUserFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserFeedArgs() interface{} {
	return user.NewUserServiceGetUserFeedArgs()
}

func newUserServiceGetUserFeedResult() interface{} {
	return user.NewUserServiceGetUserFeedResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishAction(ctx context.Context, req *user.PublishActionRequest) (r *user.PublishActionResponse, err error) {
	var _args user.UserServicePublishActionArgs
	_args.Req = req
	var _result user.UserServicePublishActionResult
	if err = p.c.Call(ctx, "PublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishList(ctx context.Context, req *user.PublishListRequest) (r *user.PublishListResponse, err error) {
	var _args user.UserServicePublishListArgs
	_args.Req = req
	var _result user.UserServicePublishListResult
	if err = p.c.Call(ctx, "PublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserFeed(ctx context.Context, req *user.FeedRequest) (r *user.FeedResponse, err error) {
	var _args user.UserServiceGetUserFeedArgs
	_args.Req = req
	var _result user.UserServiceGetUserFeedResult
	if err = p.c.Call(ctx, "GetUserFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
