// Code generated by hertz generator.

package api

import (

	"context"
	// "fmt"
	"github.com/1359332949/douyin/cmd/api/biz/model/api"
	// "github.com/1359332949/douyin/cmd/api/biz/mw"
	"github.com/1359332949/douyin/cmd/api/biz/rpc"
	// "log"
	"github.com/1359332949/douyin/kitex_gen/favorite"
	// "github.com/1359332949/douyin/kitex_gen/message"
	"github.com/1359332949/douyin/pkg/consts"
	"github.com/1359332949/douyin/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	// "path/filepath"
)

// FavoriteAction .
// @router /douyin/favorite/action/ [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	// if req.ActionType != 1{
	// 	SendResponse(c, errno.Success, nil)
	// 	return
	// }
	err = rpc.FavoriteAction(context.Background(), &favorite.FavoriteActionRequest{
		UserId:  v.(*api.User).ID,
		Token: req.Token,
		VideoId: req.VideoID,
		ActionType: req.ActionType,
		

	})
	
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	
	SendResponse(c, errno.Success, nil)
}

// FavoriteList .
// @router /douyin/favorite/list/ [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteListRequest
	err = c.BindAndValidate(&req)
	
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	video_list, err := rpc.FavoriteList(context.Background(), &favorite.FavoriteListRequest{
		UserId: v.(*api.User).ID,
		Token: req.Token,
		

	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	// SendResponse(c, errno.Success, nil)
	Err := errno.ConvertErr(errno.Success)
	c.JSON(200, utils.H{
		"status_code": Err.ErrCode,
		"status_msg":  Err.ErrMsg,
		"video_list":  video_list,
	})
}


